### ISSUE TITLE
Bootslap script is not taking in the correct github username

### ISSUE THREAD

**Issue by virajkulkarni14** [mroth/bootslap#5]
Hi @mroth 

I'm hacking at your script to customize it for my organization. When I run it locally, it asks my GitHub credentials and then while running playbooks, it throws the error 
"Cloning into '/Users/vkulkarni/src/bootslap'...
remote: Repository not found.
fatal: repository 'https://github.com/vkulkarni/bootslap.git/' not found"

My correct Github username is virajkulkarni14, but my system/login username is vkulkarni as you can see in the attached screenshot.

How do I fix this? Can you please help me? I will be pushing this script out for testing tommorow!

Thanks!
![screen shot 2015-06-04 at 4 35 30 pm 2](https://cloud.githubusercontent.com/assets/1186610/7996732/90881b66-0ad8-11e5-90f1-59672c8e8c8a.png)

**Comment by mroth** [comment]
If you check out this blob in the original script (I'm assuming you made modifications since you error was on line 102 and I only have 99 lines) you can see the relevant lines:
https://github.com/mroth/bootslap/blob/7d76a28513226e23fb21144624a501c15c2b9594/bootslap.sh#L3-L10

You can see there my script attempts to guess  the remote repo based on the system `$USER`.  If you think it's going to guess wrong (in your case it will), you can override by setting the `$BOOTSLAP_REPO` environment variable.

**Comment by virajkulkarni14** [comment]
Hello @mroth !

Sorry for the late response, but yes, that was an easy fix! :+1: 
Thanks, but even for the dotfiles, it is looking for an ansible userid attribute: `ansible_user_id`.
This is also defaulting to my system name, any idea about how to configure this?

Thank you for the help, I appreciate it! :relaxed:
